require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end

# class CreateShows < ActiveRecord::Migration[6.1]
#   def change
    
#     create_table :shows do |t|
#       t.string :name
#       t.string :network
#       t.string :day
#       t.integer :rating
  
  
  
  
  
  
  
  
#     end
#   end

# end